AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OpeningHours:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.handler.handler
      Runtime: python3.6
      CodeUri: './build/opening_hours.zip'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /openinghours/
            Method: get