AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  OpeningHours:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: python2.7
      CodeUri: './opening_hours'
      Events:
        Api:
          Type: Api
          Properties:
            Path: /openinghours
            Method: get